# Generated by Django 3.2.5 on 2021-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210802_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='discount',
        ),
    ]
