# Generated by Django 3.2.5 on 2021-08-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_featured_product_id_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
