# Generated by Django 3.2.5 on 2021-08-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_order_id_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection_id',
            new_name='collection',
        ),
    ]
